services: 
  api: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    # command: sh -c "sleep 1100"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=cms_backend_senha
      - DB_NAME=cms_backend_banco
      - DB_PORT=3306
    ports:
      - 5001:3001
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits: 
          cpus: '0.3'
          memory: '300MB'
    networks:
      - network-node

  front: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    # command: sh -c "sleep 1100"
    environment:
      - HOST_CMS_API=http://api:3001
    ports:
      - 5000:3000
    depends_on:
      - api
    deploy:
      resources:
        limits: 
          cpus: '0.3'
          memory: '300MB'
    networks:
      - network-node
      
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: cms_backend_senha
      MYSQL_DATABASE: cms_backend_banco
    ports:
      - "3306:3306"  # Map host port to container port
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$cms_backend_senha' ]
      timeout: 20s
      retries: 10
    networks:
      - network-node

networks:
  network-node:
    name: network-node